apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishubaks-a2ae"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishubaks-a2ae"
  template:
    metadata:
      labels:
        app: "aatiwarishubaks-a2ae"
    spec:
      containers:
        - name: "aatiwarishubaks-a2ae"
          image: "aaaatiwarishubregistry.azurecr.io/aatiwarishubaksa2ae"
          ports:
          - containerPort: 808