apiVersion: v1
kind: Service
metadata:
    name: "aatiwarishubaks-886b"
    labels:
        app: "aatiwarishubaks-886b"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "aatiwarishubaks-886b"